# Generated by Django 4.1.2 on 2023-05-09 13:45

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_app', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким алиасом уже существует.'}, help_text='Обязательное поле. 50 символов и менее: буквы, цифры и @/./+/-/_ ', max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
