# Generated by Django 4.2.1 on 2023-07-31 13:36

from django.db import migrations, models
import welcome_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_app', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким алиасом уже существует.'}, help_text='Обязательное поле. 50 символов и менее: буквы, цифры и @/./+/-/_ ', max_length=50, unique=True, validators=[welcome_app.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
