# Generated by Django 4.1.2 on 2022-10-09 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customing_app', '0002_alter_profile_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='colors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customing_app.colorscheme'),
        ),
    ]
