# Generated by Django 4.1.2 on 2022-10-09 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customing_app', '0004_alter_colorscheme_table_alter_link_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorscheme',
            options={'verbose_name': 'цветовая схема', 'verbose_name_plural': 'цветовые схемы'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'ссылка', 'verbose_name_plural': 'ссылки'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'профиль', 'verbose_name_plural': 'профили'},
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customing_app.profile'),
        ),
    ]
