# Generated by Django 4.1.2 on 2022-10-17 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customing_app', '0005_alter_colorscheme_options_alter_link_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorscheme',
            options={'verbose_name': 'цветовую схему', 'verbose_name_plural': 'цветовые схемы'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'ссылку', 'verbose_name_plural': 'ссылки'},
        ),
        migrations.RemoveField(
            model_name='link',
            name='solid',
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='background',
            field=models.CharField(default='#172C38', max_length=8, verbose_name='background'),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='button',
            field=models.CharField(default='#172C38', max_length=8, verbose_name='button'),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='button_click',
            field=models.CharField(default='#1272a5', max_length=8, verbose_name='button click'),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='button_font',
            field=models.CharField(default='#D0EEFF', max_length=8, verbose_name='button font'),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='button_hover',
            field=models.CharField(default='#1C3746', max_length=8, verbose_name='button hover'),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='card',
            field=models.CharField(default='#15151E', max_length=8, verbose_name='card'),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='font',
            field=models.CharField(default='#FFFFFF', max_length=8, verbose_name='font'),
        ),
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.CharField(default='link', max_length=100, verbose_name='иконка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=100, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=400, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customing_app.profile', verbose_name='профиль'),
        ),
    ]
