# Generated by Django 4.1.2 on 2023-05-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customing_app', '0006_alter_colorscheme_options_alter_link_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='position',
            field=models.IntegerField(null=True, verbose_name='позиция'),
        ),
    ]
