# Generated by Django 4.2.1 on 2023-05-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customing_app', '0011_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='avatar_shape',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.webp', upload_to='media'),
        ),
    ]
