# Generated by Django 4.2.1 on 2023-07-31 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customing_app', '0013_font_alter_colorscheme_avatar_shape_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorscheme',
            name='font_name',
        ),
    ]
