# Generated by Django 4.2.1 on 2023-07-31 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customing_app', '0014_remove_colorscheme_font_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='font_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customing_app.font'),
        ),
    ]
